name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pytest
        run: pip install pytest

      - name: Run Tests
        run: pytest

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        run: pylint

        continue-on-error: true


